"""Update list tbl

Revision ID: 3e0b55426e2e
Revises: c6a317fab97f
Create Date: 2024-05-05 16:54:40.350334

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3e0b55426e2e"
down_revision = "c6a317fab97f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
