"""Init db

Revision ID: 69c4d5b44593
Revises: 2549b9185415
Create Date: 2024-05-04 12:55:34.147398

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "69c4d5b44593"
down_revision = "2549b9185415"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Book",
        sa.Column("title", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("photo_book", sa.LargeBinary(), nullable=False),
        sa.Column("file_data", sa.LargeBinary(), nullable=False),
        sa.Column("id_user", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id_user", "id"),
    )
    op.create_table(
        "User",
        sa.Column("username", sa.String(length=120), nullable=False),
        sa.Column("login", sa.String(length=50), nullable=False),
        sa.Column("hasshed_password", sa.Text(), nullable=False),
        sa.Column("photo_user", sa.LargeBinary(), nullable=False),
        sa.Column("date_create", sa.DateTime(), nullable=False),
        sa.Column("date_update", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "Review",
        sa.Column("message", sa.String(length=350), nullable=False),
        sa.Column("id_user", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id_user"],
            ["User.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("Review")
    op.drop_table("User")
    op.drop_table("Book")
    # ### end Alembic commands ###
