"""Update relations

Revision ID: c6a317fab97f
Revises: 69c4d5b44593
Create Date: 2024-05-04 13:11:50.951127

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "c6a317fab97f"
down_revision = "69c4d5b44593"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("username", sa.String(length=120), nullable=False),
        sa.Column("login", sa.String(length=50), nullable=False),
        sa.Column("hasshed_password", sa.Text(), nullable=False),
        sa.Column("photo_user", sa.LargeBinary(), nullable=False),
        sa.Column("date_create", sa.DateTime(), nullable=False),
        sa.Column("date_update", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "book",
        sa.Column("title", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("photo_book", sa.LargeBinary(), nullable=False),
        sa.Column("file_data", sa.LargeBinary(), nullable=False),
        sa.Column("id_user", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id_user"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "review",
        sa.Column("message", sa.String(length=350), nullable=False),
        sa.Column("id_user", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id_user"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("Review")
    op.drop_table("Book")
    op.drop_table("User")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "User",
        sa.Column(
            "username",
            sa.VARCHAR(length=120),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "login", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
        sa.Column(
            "hasshed_password", sa.TEXT(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "photo_user",
            postgresql.BYTEA(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "date_create",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "date_update",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('\"User_id_seq\"'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="User_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_table(
        "Book",
        sa.Column(
            "title",
            sa.VARCHAR(length=120),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "description", sa.TEXT(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "photo_book",
            postgresql.BYTEA(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "file_data",
            postgresql.BYTEA(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "id_user", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column("id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id_user", "id", name="Book_pkey"),
    )
    op.create_table(
        "Review",
        sa.Column(
            "message",
            sa.VARCHAR(length=350),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "id_user", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('\"Review_id_seq\"'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["id_user"], ["User.id"], name="Review_id_user_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="Review_pkey"),
    )
    op.drop_table("review")
    op.drop_table("book")
    op.drop_table("user")
    # ### end Alembic commands ###
